apiVersion: v1
kind: ConfigMap
metadata:
  name: autopilot-config
  namespace: portworx
data:
  config.yaml: |-
    providers:
       - name: default
         type: prometheus
         params: url=http://px-prometheus:9090
    min_poll_interval: 2
